/*
 * Job
 *
 * Generated By LaravelConnect for iOS on 2017-12-03 00:14:46
 *
 */
 
import Foundation
import CoreData



@objc(Job)
public class Job: NSManagedObject {

    class var modelPath: String {       
        return "job"
    }
    
    class var primaryKey: String {       
        return "id"
    }

}


extension Job {

@NSManaged  public var defaultImage: String
@NSManaged  public var id: Int64
@NSManaged  public var jobTypeId: Int64
@NSManaged  public var userId: Int64
@NSManaged  public var jobDescription: String
@NSManaged  public var lat: Double
@NSManaged  public var lng: Double
@NSManaged  public var address: String
@NSManaged  public var hiredQuotationId: Int64
@NSManaged  public var deletedAt: NSDate
@NSManaged  public var createdAt: NSDate
@NSManaged  public var updatedAt: NSDate
@NSManaged  public var status: String
 

@NSManaged  public var user: User
@NSManaged  public var reviews: NSSet
@NSManaged  public var jobType: JobType
@NSManaged  public var jobAvailabilities: NSSet
@NSManaged  public var images: NSSet
@NSManaged  public var payment: JobPayment
@NSManaged  public var quotations: NSSet
@NSManaged  public var hiredQuotation: JobQuotation
 

// MARK: Generated accessors for reviews
@objc(addReviewsObject:)
@NSManaged  public func addToReviews(_ value: ProfessionalReview)

@objc(removeReviewsObject:)
 @NSManaged  public func removeFromReviews(_ value: ProfessionalReview)

@objc(addReviews:)
@NSManaged  public func addToReviews(_ values: NSSet)

@objc(removeReviews:)
@NSManaged  public func removeFromReviews(_ values: NSSet)

 // MARK: Generated accessors for jobAvailabilities
@objc(addJobAvailabilitiesObject:)
@NSManaged  public func addToJobAvailabilities(_ value: JobAvailability)

@objc(removeJobAvailabilitiesObject:)
 @NSManaged  public func removeFromJobAvailabilities(_ value: JobAvailability)

@objc(addJobAvailabilities:)
@NSManaged  public func addToJobAvailabilities(_ values: NSSet)

@objc(removeJobAvailabilities:)
@NSManaged  public func removeFromJobAvailabilities(_ values: NSSet)

 // MARK: Generated accessors for images
@objc(addImagesObject:)
@NSManaged  public func addToImages(_ value: JobImage)

@objc(removeImagesObject:)
 @NSManaged  public func removeFromImages(_ value: JobImage)

@objc(addImages:)
@NSManaged  public func addToImages(_ values: NSSet)

@objc(removeImages:)
@NSManaged  public func removeFromImages(_ values: NSSet)

 // MARK: Generated accessors for quotations
@objc(addQuotationsObject:)
@NSManaged  public func addToQuotations(_ value: JobQuotation)

@objc(removeQuotationsObject:)
 @NSManaged  public func removeFromQuotations(_ value: JobQuotation)

@objc(addQuotations:)
@NSManaged  public func addToQuotations(_ values: NSSet)

@objc(removeQuotations:)
@NSManaged  public func removeFromQuotations(_ values: NSSet)

  

    @nonobjc  public class func fetchRequest() -> NSFetchRequest<Job> {
        return NSFetchRequest<Job>(entityName: "Job")
    }

}
