/*
 * JobAvailability
 *
 * Generated By LaravelConnect for iOS on 2017-12-03 00:14:47
 *
 */
 
import Foundation
import CoreData



@objc(JobAvailability)
public class JobAvailability: NSManagedObject {

    class var modelPath: String {       
        return "job_availability"
    }
    
    class var primaryKey: String {       
        return "id"
    }

}


extension JobAvailability {

@NSManaged  public var id: Int64
@NSManaged  public var jobId: Int64
@NSManaged  public var from: NSDate
@NSManaged  public var to: NSDate
@NSManaged  public var isAllDay: Bool
@NSManaged  public var deletedAt: NSDate
@NSManaged  public var createdAt: NSDate
@NSManaged  public var updatedAt: NSDate
 

@NSManaged  public var job: Job
 

 

    @nonobjc  public class func fetchRequest() -> NSFetchRequest<JobAvailability> {
        return NSFetchRequest<JobAvailability>(entityName: "JobAvailability")
    }

}
