/*
 * JobImage
 *
 * Generated By LaravelConnect for iOS on 2017-12-03 00:14:46
 *
 */
 
import Foundation
import CoreData



@objc(JobImage)
public class JobImage: NSManagedObject {

    class var modelPath: String {       
        return "job_image"
    }
    
    class var primaryKey: String {       
        return "id"
    }

}


extension JobImage {

@NSManaged  public var id: Int64
@NSManaged  public var jobId: Int64
@NSManaged  public var url: String
@NSManaged  public var deletedAt: NSDate
@NSManaged  public var createdAt: NSDate
@NSManaged  public var updatedAt: NSDate
 

@NSManaged  public var job: Job
 

 

    @nonobjc  public class func fetchRequest() -> NSFetchRequest<JobImage> {
        return NSFetchRequest<JobImage>(entityName: "JobImage")
    }

}
