/*
 * JobPayment
 *
 * Generated By LaravelConnect for iOS on 2017-12-03 00:14:46
 *
 */
 
import Foundation
import CoreData



@objc(JobPayment)
public class JobPayment: NSManagedObject {

    class var modelPath: String {       
        return "job_payment"
    }
    
    class var primaryKey: String {       
        return "id"
    }

}


extension JobPayment {

@NSManaged  public var id: Int64
@NSManaged  public var userId: Int64
@NSManaged  public var professionalId: Int64
@NSManaged  public var jobId: Int64
@NSManaged  public var amount: Double
@NSManaged  public var paidWithCash: Bool
@NSManaged  public var isPaid: Bool
@NSManaged  public var deletedAt: NSDate
@NSManaged  public var createdAt: NSDate
@NSManaged  public var updatedAt: NSDate
 

@NSManaged  public var user: User
@NSManaged  public var professional: Professional
@NSManaged  public var job: Job
 

 

    @nonobjc  public class func fetchRequest() -> NSFetchRequest<JobPayment> {
        return NSFetchRequest<JobPayment>(entityName: "JobPayment")
    }

}
