/*
 * JobQuotationMessage
 *
 * Generated By LaravelConnect for iOS on 2017-12-03 00:14:47
 *
 */
 
import Foundation
import CoreData



@objc(JobQuotationMessage)
public class JobQuotationMessage: NSManagedObject {

    class var modelPath: String {       
        return "job_quotation_message"
    }
    
    class var primaryKey: String {       
        return "id"
    }

}


extension JobQuotationMessage {

@NSManaged  public var id: Int64
@NSManaged  public var userId: Int64
@NSManaged  public var jobQuotationId: Int64
@NSManaged  public var message: String
@NSManaged  public var deletedAt: NSDate
@NSManaged  public var createdAt: NSDate
@NSManaged  public var updatedAt: NSDate
 

@NSManaged  public var user: User
@NSManaged  public var quotation: JobQuotation
 

 

    @nonobjc  public class func fetchRequest() -> NSFetchRequest<JobQuotationMessage> {
        return NSFetchRequest<JobQuotationMessage>(entityName: "JobQuotationMessage")
    }

}
