/*
 * JobQuotation
 *
 * Generated By LaravelConnect for iOS on 2017-12-03 00:14:46
 *
 */
 
import Foundation
import CoreData



@objc(JobQuotation)
public class JobQuotation: NSManagedObject {

    class var modelPath: String {       
        return "job_quotation"
    }
    
    class var primaryKey: String {       
        return "id"
    }

}


extension JobQuotation {

@NSManaged  public var id: Int64
@NSManaged  public var jobId: Int64
@NSManaged  public var professionalId: Int64
@NSManaged  public var amount: Double
@NSManaged  public var mustBeConfirmed: Bool
@NSManaged  public var jobAvailabilityId: Int64
@NSManaged  public var status: String
@NSManaged  public var deletedAt: NSDate
@NSManaged  public var createdAt: NSDate
@NSManaged  public var updatedAt: NSDate
 

@NSManaged  public var job: Job
@NSManaged  public var professional: Professional
@NSManaged  public var jobAvailability: JobAvailability
@NSManaged  public var messages: NSSet
 

// MARK: Generated accessors for messages
@objc(addMessagesObject:)
@NSManaged  public func addToMessages(_ value: JobQuotationMessage)

@objc(removeMessagesObject:)
 @NSManaged  public func removeFromMessages(_ value: JobQuotationMessage)

@objc(addMessages:)
@NSManaged  public func addToMessages(_ values: NSSet)

@objc(removeMessages:)
@NSManaged  public func removeFromMessages(_ values: NSSet)

  

    @nonobjc  public class func fetchRequest() -> NSFetchRequest<JobQuotation> {
        return NSFetchRequest<JobQuotation>(entityName: "JobQuotation")
    }

}
