/*
 * Keyword
 *
 * Generated By LaravelConnect for iOS on 2017-12-03 00:14:46
 *
 */
 
import Foundation
import CoreData



@objc(Keyword)
public class Keyword: NSManagedObject {

    class var modelPath: String {       
        return "keyword"
    }
    
    class var primaryKey: String {       
        return "id"
    }

}


extension Keyword {

@NSManaged  public var id: Int64
@NSManaged  public var keyword: String
@NSManaged  public var jobTypeId: Int64
 

@NSManaged  public var jobType: JobType
 

 

    @nonobjc  public class func fetchRequest() -> NSFetchRequest<Keyword> {
        return NSFetchRequest<Keyword>(entityName: "Keyword")
    }

}
