/*
 * Professional
 *
 * Generated By LaravelConnect for iOS on 2017-12-03 00:14:46
 *
 */
 
import Foundation
import CoreData



@objc(Professional)
public class Professional: NSManagedObject {

    class var modelPath: String {       
        return "professional"
    }
    
    class var primaryKey: String {       
        return "id"
    }

}


extension Professional {

@NSManaged  public var hasBankInformation: String
@NSManaged  public var fullName: String
@NSManaged  public var averageReviewScore: String
@NSManaged  public var id: Int64
@NSManaged  public var lat: Double
@NSManaged  public var lng: Double
@NSManaged  public var distance: Double
@NSManaged  public var isVerified: Bool
@NSManaged  public var rating: Double
@NSManaged  public var reviewCount: Int64
@NSManaged  public var jobsCompleted: Int64
@NSManaged  public var waitingQuotations: Int64
@NSManaged  public var answeredQuotations: Int64
@NSManaged  public var hiredQuotations: Int64
@NSManaged  public var titleId: Int64
@NSManaged  public var deletedAt: NSDate
@NSManaged  public var createdAt: NSDate
@NSManaged  public var updatedAt: NSDate
 

@NSManaged  public var user: User
@NSManaged  public var title: Skill
@NSManaged  public var reviews: NSSet
@NSManaged  public var quotations: NSSet
@NSManaged  public var payments: NSSet
 

// MARK: Generated accessors for reviews
@objc(addReviewsObject:)
@NSManaged  public func addToReviews(_ value: ProfessionalReview)

@objc(removeReviewsObject:)
 @NSManaged  public func removeFromReviews(_ value: ProfessionalReview)

@objc(addReviews:)
@NSManaged  public func addToReviews(_ values: NSSet)

@objc(removeReviews:)
@NSManaged  public func removeFromReviews(_ values: NSSet)

 // MARK: Generated accessors for quotations
@objc(addQuotationsObject:)
@NSManaged  public func addToQuotations(_ value: JobQuotation)

@objc(removeQuotationsObject:)
 @NSManaged  public func removeFromQuotations(_ value: JobQuotation)

@objc(addQuotations:)
@NSManaged  public func addToQuotations(_ values: NSSet)

@objc(removeQuotations:)
@NSManaged  public func removeFromQuotations(_ values: NSSet)

 // MARK: Generated accessors for payments
@objc(addPaymentsObject:)
@NSManaged  public func addToPayments(_ value: JobPayment)

@objc(removePaymentsObject:)
 @NSManaged  public func removeFromPayments(_ value: JobPayment)

@objc(addPayments:)
@NSManaged  public func addToPayments(_ values: NSSet)

@objc(removePayments:)
@NSManaged  public func removeFromPayments(_ values: NSSet)

  

    @nonobjc  public class func fetchRequest() -> NSFetchRequest<Professional> {
        return NSFetchRequest<Professional>(entityName: "Professional")
    }

}
