/*
 * ProfessionalReview
 *
 * Generated By LaravelConnect for iOS on 2017-12-03 00:14:47
 *
 */
 
import Foundation
import CoreData



@objc(ProfessionalReview)
public class ProfessionalReview: NSManagedObject {

    class var modelPath: String {       
        return "professional_review"
    }
    
    class var primaryKey: String {       
        return "id"
    }

}


extension ProfessionalReview {

@NSManaged  public var id: Int64
@NSManaged  public var userId: Int64
@NSManaged  public var professionalId: Int64
@NSManaged  public var jobId: Int64
@NSManaged  public var score: Int64
@NSManaged  public var professionalReviewDescription: String
@NSManaged  public var deletedAt: NSDate
@NSManaged  public var createdAt: NSDate
@NSManaged  public var updatedAt: NSDate
 

@NSManaged  public var user: User
@NSManaged  public var professional: Professional
@NSManaged  public var job: Job
 

 

    @nonobjc  public class func fetchRequest() -> NSFetchRequest<ProfessionalReview> {
        return NSFetchRequest<ProfessionalReview>(entityName: "ProfessionalReview")
    }

}
