/*
 * Skill
 *
 * Generated By LaravelConnect for iOS on 2017-12-03 00:14:46
 *
 */
 
import Foundation
import CoreData



@objc(Skill)
public class Skill: NSManagedObject {

    class var modelPath: String {       
        return "skill"
    }
    
    class var primaryKey: String {       
        return "id"
    }

}


extension Skill {

@NSManaged  public var id: Int64
@NSManaged  public var name: String
@NSManaged  public var skillDescription: String
@NSManaged  public var parentId: Int64
@NSManaged  public var deletedAt: NSDate
@NSManaged  public var createdAt: NSDate
@NSManaged  public var updatedAt: NSDate
 

@NSManaged  public var children: NSSet
@NSManaged  public var parent: Skill
@NSManaged  public var professionalsWithTitle: NSSet
 

// MARK: Generated accessors for children
@objc(addChildrenObject:)
@NSManaged  public func addToChildren(_ value: Skill)

@objc(removeChildrenObject:)
 @NSManaged  public func removeFromChildren(_ value: Skill)

@objc(addChildren:)
@NSManaged  public func addToChildren(_ values: NSSet)

@objc(removeChildren:)
@NSManaged  public func removeFromChildren(_ values: NSSet)

 // MARK: Generated accessors for professionalsWithTitle
@objc(addProfessionalsWithTitleObject:)
@NSManaged  public func addToProfessionalsWithTitle(_ value: Professional)

@objc(removeProfessionalsWithTitleObject:)
 @NSManaged  public func removeFromProfessionalsWithTitle(_ value: Professional)

@objc(addProfessionalsWithTitle:)
@NSManaged  public func addToProfessionalsWithTitle(_ values: NSSet)

@objc(removeProfessionalsWithTitle:)
@NSManaged  public func removeFromProfessionalsWithTitle(_ values: NSSet)

  

    @nonobjc  public class func fetchRequest() -> NSFetchRequest<Skill> {
        return NSFetchRequest<Skill>(entityName: "Skill")
    }

}
